name: Publish GitHub Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
          
      - name: Install dependencies
        run: dotnet restore

      - name: Run a multi-line script
        run: |
          dotnet pack src/NvimClient.API/NvimClient.API.csproj --configuration Release
          dotnet nuget push "src/NvimClient.API/bin/Release/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
