name: Test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    env:
      CONFIGURATION: Release
      TEST_PROJECT: test/Nvim.Client.Test/Nvim.Client.Test.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: >
          dotnet build
          --configuration "$CONFIGURATION"
          --no-restore
          -p:ContinuousIntegrationBuild=true

      - name: Test
        run: >
          dotnet test
          --project "$TEST_PROJECT"
          --configuration "$CONFIGURATION"
          --no-build
          --no-restore
          --minimum-expected-tests 1
          --timeout 60s
